name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # or any other node version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build # or whatever build command you have

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/ # or your build output directory

  deploy:
    needs: build # ensure build job finishes successfully before deploy job starts
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # only run on pushes to main branch

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: dist/

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10 # or any other deployment action
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /var/www/my-app # or your deployment path
            rm -rf *
            cp -r dist/* .
            # restart services or run any other deployment steps
            # Example:
            # sudo systemctl restart my-app
